# configs/faster_rcnn.yaml
_base_: base_config.yaml # 상속 명시

# Faster R-CNN 전용 설정

model:
  name: "faster_rcnn"
  backbone: "resnet50"

  # Faster R-CNN 특화 설정
  anchor_sizes: [[32], [64], [128], [256], [512]]
  aspect_ratios: [0.5, 1.0, 2.0]

  # RPN 설정
  rpn_pre_nms_top_n_train: 2000
  rpn_pre_nms_top_n_test: 1000
  rpn_post_nms_top_n_train: 2000
  rpn_post_nms_top_n_test: 1000
  rpn_nms_thresh: 0.7

  # ROI 설정
  box_score_thresh: 0.05
  box_nms_thresh: 0.5
  box_detections_per_img: 100

# 학습 설정 (Faster R-CNN에 최적화)
training:
  batch_size: 8 # 메모리 사용량이 높음
  epochs: 1
  learning_rate: 0.005
  gradient_clip: 5.0
